from flask import Flask, render_template
from flask_mail import Mail
from config import config
import os
import datetime

# Initialize Flask extensions
mail = Mail()
# Define placeholder data (replace with database/CMS later)
# Example - this could also be loaded from JSON/YAML files
PROJECTS_DATA = {
    'dcis': {
        'name': 'DCIS: Drone Cloud Intelligence System',
        'short_desc': 'Autonomous drone solutions for enhanced intelligence gathering and operations.',
        'long_desc': 'Our Drone Cloud Intelligence System (DCIS) represents the pinnacle of 6th generation AI-powered drone technology. This advanced system integrates cloud computing with autonomous drone operations, enabling unprecedented capabilities in data processing, decision-making, and mission execution.',
        'images': ['img/dcis_1.jpg', 'img/dcis_2.jpg', 'img/dcis_3.jpg'],
        'technologies': ['Cloud Computing', 'AI/ML', 'Autonomous Flight', 'Real-time Data'],
        'slug': 'dcis',
        'has_dedicated_page': True,
        'features': ['Real-Time Fleet Management', 'AI-Driven Autonomy', 'Cloud-based Data Processing', 'Enhanced Safety Protocols']
    },
    'utms': {
        'name': 'UTMS: Unmanned Traffic Management System',
        'short_desc': 'Advanced system for managing drone traffic safely and efficiently.',
        'long_desc': 'Our Unmanned Traffic Management System (UTMS) provides a comprehensive solution for coordinating and managing drone traffic in urban and rural environments. This system ensures safe, efficient, and compliant operations for multiple drone operators in shared airspace.',
        'images': ['img/utms_1.jpg', 'img/utms_2.jpg', 'img/utms_3.jpg'],
        'technologies': ['Air Traffic Control', 'Geofencing', 'Real-time Tracking', 'Conflict Resolution'],
        'slug': 'utms',
        'has_dedicated_page': True,
        'features': ['Real-time Traffic Monitoring', 'Airspace Management', 'Regulatory Compliance', 'Collision Avoidance']
    },

    # 'vidya-connect': {
    #     'name': 'Vidya Connect',
    #     'short_desc': 'Providing Internet Connectivity anywhere in India using satellite, but only for educational purposes with an inbuilt AI model.',
    #     'long_desc': 'Vidya Connect is a revolutionary system that leverages satellite technology to provide internet connectivity across India, specifically designed for educational purposes. The system includes an inbuilt AI model that optimizes connectivity and filters content for educational use.',
    #     'images': ['img/vidya_connect_1.jpg', 'img/vidya_connect_2.jpg', 'img/vidya_connect_3.jpg'],
    #     'technologies': ['Satellite Communication', 'AI Content Filtering', 'Educational Technology'],
    #     'slug': 'vidya-connect',
    #     'has_dedicated_page': True,
    #     'features': ['Nationwide educational connectivity', 'AI-powered content filtering', 'Low-cost deployment', 'Remote area accessibility']
    # },
    # 'vertical-axis-turbine': {
    #     'name': 'Vertical Axis Wind Turbine',
    #     'short_desc': 'This is the Vertical Axis Wind Turbine, which will be placed in the middle of the road on top of the street light pole.',
    #     'long_desc': 'Our innovative Vertical Axis Wind Turbine design is specifically engineered to be mounted on street light poles in the middle of roads. This placement allows the turbines to harness wind energy generated by passing vehicles as well as natural wind, providing a sustainable power source for street lighting and other urban infrastructure.',
    #     'images': ['img/vertical_axis_turbine_1.jpg', 'img/vertical_axis_turbine_2.jpg', 'img/vertical_axis_turbine_3.jpg'],
    #     'technologies': ['Renewable Energy', 'Urban Infrastructure', 'Sustainable Design'],
    #     'slug': 'vertical-axis-turbine',
    #     'has_dedicated_page': True,
    #     'features': ['Vehicle-induced wind energy capture', 'Integrated street lighting', 'Low maintenance design', 'Urban energy independence']
    # }
    # Add more projects
}

NEWS_DATA = [
    {'id': 1, 'title': 'BeRAM Launches Revolutionary DCIS Platform', 'date': '2024-10-26', 'summary': 'Our new Drone Cloud Intelligence System is set to transform...', 'image': 'img/news_dcis.jpg', 'slug': 'beram-launches-dcis'},
    {'id': 2, 'title': 'Successful UTMS Trials Conducted Over Cityscape', 'date': '2024-09-15', 'summary': 'Loren ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore.', 'image': 'img/news_utms.jpg', 'slug': 'successful-utms-trials'},
    {'id': 3, 'title': 'BeRAM Announces Vidya Connect Initiative', 'date': '2024-08-20', 'summary': 'Bringing educational internet connectivity to remote areas across India through innovative satellite technology.', 'image': 'img/news_vidya.jpg', 'slug': 'beram-announces-vidya-connect'},
    # Add more news items
]

SOLUTIONS_DATA = {
   
    'dcis': {
        'name': 'Short-Range Drone Delivery',
        'icon': 'fas fa-cloud',
        'desc': 'From Godown to Doorstep',
        'slug': 'dcis',
        'image': 'img/DroneDelivery.jpeg',
        'long_desc': 'Our Drone Cloud Intelligence System (DCIS) represents the pinnacle of 6th generation AI-powered drone technology. This advanced system integrates cloud computing with autonomous drone operations, enabling unprecedented capabilities in data processing, decision-making, and mission execution.<br><br><ul><li>Real-Time Fleet Management: Utilize cloud-based infrastructure and 5G connectivity for seamless tracking, monitoring, and control of multiple drones, ensuring operational efficiency and safety.</li><li>AI-Driven Autonomy: Leverage advanced AI and machine learning for autonomous flight path planning, collision avoidance, and predictive maintenance, enhancing reliability and performance.</li><li>Versatile Applications: Enable precision agriculture, surveillance, logistics, and environmental monitoring with high-resolution data acquisition and real-time analytics.</li></ul>',
        'features': ['Real-Time Fleet Management: Utilize cloud-based infrastructure and 5G connectivity for seamless tracking, monitoring, and control of multiple drones, ensuring operational efficiency and safety.', 'AI-Driven Autonomy: Leverage advanced AI and machine learning for autonomous flight path planning, collision avoidance, and predictive maintenance, enhancing reliability and performance.', 'Versatile Applications: Enable precision agriculture, surveillance, logistics, and environmental monitoring with high-resolution data acquisition and real-time analytics.'],
        'has_dedicated_page': True
    },
    'utms': {
        'name': 'Long-Range Drone Delivery',
        'icon': 'fas fa-traffic-light',
        'desc': 'From Godown To Godown',
        'slug': 'utms',
        'image': 'img/drone_airspace.jpg',
        'long_desc': 'Our Unmanned Traffic Management System (UTMS) provides a comprehensive solution for coordinating and managing drone traffic in urban and rural environments. This system ensures safe, efficient, and compliant operations for multiple drone operators in shared airspace.<br><br><ul><li>Real-time traffic monitoring and coordination</li><li>Seamless integration with urban infrastructure</li><li>AI-driven predictive analytics for traffic optimization</li></ul>',
        'features': ['Real-time traffic monitoring and coordination', 'Seamless integration with urban infrastructure', 'AI-driven predictive analytics for traffic optimization'],
        'has_dedicated_page': True
    },
    'agriculture': {
        'name': 'Agriculture',
        'icon': 'fas fa-seedling',
        'desc': 'Precision farming, crop monitoring, spraying',
        'slug': 'agriculture',
        'image': 'img/solution_agriculture.jpg',
        'long_desc': 'Utilize drones for aerial mapping, soil analysis, crop health monitoring, and targeted pesticide/fertilizer spraying to optimize yields and reduce resource usage.',
        'features': ['Aerial mapping and soil analysis', 'Crop health monitoring', 'Targeted pesticide and fertilizer spraying'],
        'has_dedicated_page': True
    },
    # 'energy': {
    #     'name': 'Energy & Utilities',
    #     'icon': 'fas fa-bolt',
    #     'desc': 'Infrastructure inspection, pipeline monitoring',
    #     'slug': 'energy',
    #     'image': 'img/solution_energy.jpg',
    #     'long_desc': 'Conduct safe and efficient inspections of power lines, wind turbines, solar farms, and pipelines. Detect anomalies early and reduce downtime.',
    #     'features': ['Power line and infrastructure inspection', 'Wind turbine and solar farm monitoring', 'Early anomaly detection and preventive maintenance'],
    #     'has_dedicated_page': True
    # },
    # 'construction': {
    #     'name': 'Construction & Infrastructure',
    #     'icon': 'fas fa-hard-hat',
    #     'desc': 'Site surveying, progress monitoring',
    #     'slug': 'construction',
    #     'image': 'img/solution_construction.jpg',
    #     'long_desc': 'Perform rapid site surveys, create accurate 3D models, monitor construction progress, and ensure safety compliance with aerial data.',
    #     'features': ['Rapid site surveys and 3D modeling', 'Construction progress monitoring', 'Safety compliance and risk assessment'],
    #     'has_dedicated_page': True
    # },
    # # --- Add images and details for other solutions ---
    # 'security': {
    #     'name': 'Security & Surveillance',
    #     'icon': 'fas fa-shield-alt',
    #     'desc': 'Perimeter monitoring, event security',
    #     'slug': 'security',
    #     'image': 'img/solution_security.jpg',
    #     'long_desc': 'Enhance security operations with aerial surveillance for large areas, perimeter monitoring, crowd management, and incident response.',
    #     'features': ['Perimeter monitoring and intrusion detection', 'Event security and crowd management', 'Real-time incident response and situational awareness'],
    #     'has_dedicated_page': True
    # },
    # 'logistics': {
    #      'name': 'Delivery & Logistics',
    #      'icon': 'fas fa-shipping-fast',
    #      'desc': 'Medical supply delivery, remote area transport',
    #      'slug': 'logistics',
    #      'image': 'img/solution_logistics.jpg',
    #      'long_desc': 'Enable rapid delivery of essential goods, medical supplies, and packages to remote or hard-to-reach locations, bypassing traditional infrastructure limitations.',
    #      'features': ['Medical supply and emergency delivery', 'Last-mile package delivery', 'Remote area access and transportation'],
    #      'has_dedicated_page': True
    #  },
    #  'mapping': {
    #      'name': 'Mapping & Surveying',
    #      'icon': 'fas fa-map-marked-alt',
    #      'desc': 'High-resolution maps, 3D modeling',
    #      'slug': 'mapping',
    #      'image': 'img/solution_mapping.jpg',
    #      'long_desc': 'Generate detailed orthomosaic maps, digital elevation models (DEMs), and 3D point clouds for land management, urban planning, environmental studies, and more.',
    #      'features': ['High-resolution orthomosaic mapping', 'Digital elevation models (DEMs) and 3D point clouds', 'Land management and urban planning support'],
    #      'has_dedicated_page': True
    #  }
    # Add more solutions based on Garuda/Meta examples if needed
}


def create_app(config_name='default'):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(config[config_name])

    # Initialize config-specific settings if available
    if hasattr(config[config_name], 'init_app'):
        config[config_name].init_app(app)

    # Ensure instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    # Initialize Flask extensions
    mail.init_app(app)

    # Register Blueprints
    from beram.main.routes import main_bp
    from beram.projects.routes import projects_bp
    from beram.solutions.routes import solutions_bp
    from beram.news.routes import news_bp

    app.register_blueprint(main_bp)
    app.register_blueprint(projects_bp, url_prefix='/projects')
    app.register_blueprint(solutions_bp, url_prefix='/solutions')
    app.register_blueprint(news_bp, url_prefix='/news')

    # --- Register Global Context Processors ---
    # Make data available to all templates easily
    @app.context_processor
    def inject_global_data():  # noqa
        return dict(
            all_projects=PROJECTS_DATA,
            all_solutions=SOLUTIONS_DATA,
            now=datetime.datetime.now(datetime.timezone.utc)  # Using timezone-aware UTC time
            # Pass only essential footer data if needed
        )

    # Initialize error handlers and logging
    from beram.errors import init_error_handlers, init_logging
    init_error_handlers(app)
    init_logging(app)

    # Initialize security features
    from beram.security import init_security
    init_security(app)

    return app